blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://stackoverflow.com/questions/tagged/spring-tools-4
    about: Please ask and answer questions on StackOverflow with the tag spring-tools-4