sleep: &sleep
  config:
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: alpine
        tag: latest
    run:
      path: sh
      args:
      - -exc
      - sleep 60

##########

resource_types:
- name: pool
  type: docker-image

jobs:
- name: acquire-1
  plan:
    - task: sleep
      <<: *sleep
