platform: linux
image_resource:
  type: registry-image
  source:
    username: ((docker_hub_username))
    password: ((docker_hub_password))
    repository: springci/sts4-build-env
params:
  ovsx_token: ovsx_token_should_be_set
inputs:
- name: tasks
- name: sts4
run:
  path: tasks/concourse/tasks/ovsx-build-and-publish.sh