platform: linux
image_resource:
  type: registry-image
  source:
    username: ((docker_hub_username))
    password: ((docker_hub_password))
    repository: springci/sts4-build-env
inputs:
- name: sts4
- name: s3-concourse-vsix-snapshot
- name: s3-spring-boot-vsix-snapshot
- name: s3-bosh-vsix-snapshot
- name: s3-manifest-yaml-vsix-snapshot
outputs:
- name: output
run:
  path: sts4/concourse/tasks/prepare-theia-docker-image.sh